class ExerciseDatabase {
  static const List<String> globalExerciseList = [
    'PRESS BANCA',
    'PRESS INCLINADO',
    'PRESS MILITAR',
    'SENTADILLA',
    'PESO MUERTO',
    'JALÓN AL PECHO',
    'REMO CON BARRA',
    'CURL DE BICEPS',
    'EXTENSIÓN DE TRICEPS',
    'PRESS FRANCES',
    'APERTURAS',
    'LATERALES',
    'ZANCADAS',
    'DOMINADAS',
    'REMO EN T'
  ];

  static const Map<String, List<String>> defaultExerciseDb = {
    'PUSH (EMPUJE)': ['PRESS BANCA', 'PRESS MILITAR', 'EXTENSIÓN DE TRICEPS', 'LATERALES', 'APERTURAS'],
    'PULL (TIRÓN)': ['JALÓN AL PECHO', 'REMO EN T', 'PULL OVER', 'CURL DE BICEPS', 'MARTILLO'],
    'LEGS (PIERNA)': ['SENTADILLA', 'PESO MUERTO', 'EXTENSIÓN', 'FEMORAL TUMBADO', 'GEMELO'],
    'ARNOLD (PECHO/ESPALDA)': ['PRESS BANCA', 'JALÓN AL PECHO', 'PRESS INCLINADO', 'REMO CON BARRA', 'DOMINADAS'],
    'ARNOLD (HOMBROS/BRAZOS)': ['PRESS MILITAR', 'CURL DE BICEPS', 'EXTENSIÓN DE TRICEPS', 'CURL MARTILLO', 'PRESS FRANCES', 'LATERALES'],
    'TORSO': ['PRESS BANCA', 'JALÓN AL PECHO ABIERTO', 'PRESS INCLINADO', 'REMO EN T'],
    'PIERNA': ['ADDUCTOR', 'HAKA', 'FEMORAL TUMBADO', 'EXTENSIÓN', 'FEMORAL SENTADO'],
    'FULL BODY': ['SENTADILLA', 'PRESS BANCA', 'JALÓN AL PECHO', 'PRESS MILITAR', 'CURL DE BICEPS'],
  };

  static const Map<String, List<String>> routineStructures = {
    'PUSH PULL LEG': ['PUSH (EMPUJE)', 'PULL (TIRÓN)', 'LEGS (PIERNA)'],
    'FULL BODY': ['FULL BODY'],
    'UPPER LOWER': ['TORSO', 'PIERNA'],
    'ARNOLD SPLIT': ['ARNOLD (PECHO/ESPALDA)', 'ARNOLD (HOMBROS/BRAZOS)', 'PIERNA'],
    'MI MEZCLA (ARNOLD+PPL)': ['PUSH (EMPUJE)', 'PULL (TIRÓN)', 'LEGS (PIERNA)', 'ARNOLD (PECHO/ESPALDA)', 'ARNOLD (HOMBROS/BRAZOS)'],
    'PERSONALIZADO': [],
  };

  static const List<String> defaultGroups = ['PUSH (EMPUJE)', 'PULL (TIRÓN)', 'LEGS (PIERNA)', 'ARNOLD (PECHO/ESPALDA)', 'ARNOLD (HOMBROS/BRAZOS)'];
}
